import Head from "next/head";
import useSWR from "swr";
import { Data } from "./api/data";

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function Home() {
  const { data, error } = useSWR<Data>("/api/data", fetcher);

  if (error) return <p>whoops something broke</p>;

  return (
    <div>
      <Head>
        <title>PS ♥️ Musikhjälpen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">PS ♥️ Musikhjälpen</h1>
        <p>Total amount: {data?.totalAmount}</p>
        <p>
          Top donator: {data?.topD?.name} who donated {data?.topD?.amount} (
          {data?.topD?.message}){" "}
        </p>

        {data?.offices.map((office) => (
          <>
            <p>
              {office.name} has donated a total of {office.totalAmount} with the
              top D being: {office.topD?.name} who donated {office.topD?.amount}{" "}
              ({office.topD?.message}){" "}
            </p>
          </>
        ))}
      </main>
    </div>
  );
}
